apiVersion: v1
kind: Secret
metadata:
  name: aws-backup-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.awsBackup.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.awsBackup.secretAccessKey | quote }}
