apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: family-task-app-sa
      imagePullSecrets:
        - name: gitlab-registry-cred
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.frontend.port }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            requests:
              cpu: {{ .Values.frontend.resources.requests.cpu | quote }}
              memory: {{ .Values.frontend.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.frontend.resources.limits.cpu | quote }}
              memory: {{ .Values.frontend.resources.limits.memory | quote }}
