apiVersion: v1
kind: Secret
metadata:
  name: family-task-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_USER: {{ .Values.secrets.dbUser | quote }}
  {{- if not .Values.vault.enabled }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  {{- end }}
