apiVersion: v1
kind: Secret
metadata:
  name: family-task-secrets
  namespace: family-task-app
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "REPLACE_ME"
  JWT_SECRET: "REPLACE_ME_WITH_LONG_RANDOM_STRING"
