namespace: family-task-app

frontend:
  image: registry.gitlab.com/elvir.osmanov.1989/linatrixsite/frontend:44f38182
  replicas: 1
  port: 80
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "200m"
      memory: "128Mi"

backend:
  image: registry.gitlab.com/elvir.osmanov.1989/linatrixsite/backend:44f38182
  replicas: 1
  port: 3000
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"

postgres:
  image: postgres:16-alpine
  port: 5432
  storageSize: 1Gi
  storageClassName: local-path

config:
  dbHost: "postgres"
  dbPort: "5432"
  dbName: "family_task_app"
  backendPort: "3000"

secrets:
  dbUser: "postgres"
  dbPassword: "m9cJyIuZ8B0JW+rf4QqDVzb+ResH700h"
  jwtSecret: "N2/X+CoszLQp4QP38iWTyyW4ve22PH5QIlWDKLW9WJ4="

ingress:
  host: linatrixsite.local
  className: nginx

